# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileCopyrightText: Copyright 2026 Jonas I. Liechti <j-i-l@t4d.ch>

# Layer 4/5: Bioconductor (BiocManager + Rgraphviz).
#
# Installs the Bioconductor toolchain on top of the inla layer using the
# shared install_bioc.sh script.

ARG BASE_IMAGE
FROM ${BASE_IMAGE}

LABEL org.opencontainers.image.licenses="GPL-3.0-only" \
      org.opencontainers.image.authors="Jonas I. Liechti <j-i-l@t4d.ch>"

COPY shared/install_bioc.sh /tmp/install_bioc.sh
RUN chmod +x /tmp/install_bioc.sh && /tmp/install_bioc.sh
