# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileCopyrightText: Copyright 2026 Jonas I. Liechti <j-i-l@t4d.ch>

# Fedora system-library base. JAGS is installed in the jags layer.

ARG R_VERSION
ARG RHUB_IMAGE=gcc16
FROM ghcr.io/r-hub/containers/${RHUB_IMAGE}:latest

LABEL org.opencontainers.image.description="R-hub-based image with system libraries for R packages."
LABEL org.opencontainers.image.licenses="GPL-3.0-only"
LABEL org.opencontainers.image.authors="Jonas I. Liechti <j-i-l@t4d.ch>"
LABEL org.opencontainers.image.source="https://github.com/furrer-lab/r-containers"
LABEL org.opencontainers.image.documentation="https://github.com/furrer-lab/r-containers"
LABEL org.opencontainers.image.vendor="Furrer Lab"

ARG R_VERSION

RUN dnf -y upgrade && dnf -y install \
  cmake git openssh-clients gcc-gfortran pkgconf libpkgconf-devel \
  openssl-devel libcurl-devel libuv-devel \
  fontconfig-devel harfbuzz-devel fribidi-devel freetype-devel \
  libpng-devel libtiff-devel libjpeg-devel libwebp-devel libxml2-devel \
  gsl-devel sqlite-devel NLopt-devel \
  lapack\* blas\* atlas\* flexiblas-devel abseil-cpp-devel \
  udunits2-devel gdal-devel geos-devel proj-devel \
  ImageMagick-c++-devel pandoc curl

ENV PATH="/opt/R-$R_VERSION/bin:${PATH}"
ENV R_LIBS_USER=" "
ENV RENV_CONFIG_AUTOLOADER_ENABLED=false

RUN R_HOME=$(R RHOME) && \
    if [ -d "${R_HOME}/library/base/R" ]; then \
      echo 'options(repos = c(CRAN = "https://cran.rstudio.com"))' >> ${R_HOME}/library/base/R/Rprofile; \
    elif [ -d "${R_HOME}/etc" ]; then \
      echo 'options(repos = c(CRAN = "https://cran.rstudio.com"))' >> ${R_HOME}/etc/Rprofile.site; \
    else exit 1; fi
