# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileCopyrightText: Copyright 2026 Jonas I. Liechti <j-i-l@t4d.ch>

ARG BASE_IMAGE
FROM ${BASE_IMAGE}
LABEL org.opencontainers.image.licenses="GPL-3.0-only" \
      org.opencontainers.image.authors="Jonas I. Liechti <j-i-l@t4d.ch>"
COPY shared/install_bioc.sh /tmp/install_bioc.sh
RUN chmod +x /tmp/install_bioc.sh && /tmp/install_bioc.sh
